move from sambaFull to samba
error:
       … while calling the 'head' builtin
         at /nix/store/anvdcc2arw7kqrvwnidvhw6ypkkvws68-source/lib/attrsets.nix:1712:13:
         1711|           if length values == 1 || pred here (elemAt values 1) (head values) then
         1712|             head values
             |             ^
         1713|           else

       … while evaluating the attribute 'value'
         at /nix/store/anvdcc2arw7kqrvwnidvhw6ypkkvws68-source/lib/modules.nix:1159:7:
         1158|     // {
         1159|       value = addErrorContext "while evaluating the option `${showOption loc}':" value;
             |       ^
         1160|       inherit (res.defsFinal') highestPrio;

       … while evaluating the option `system.build.toplevel':

       … while evaluating definitions from `/nix/store/anvdcc2arw7kqrvwnidvhw6ypkkvws68-source/nixos/modules/system/activation/top-level.nix':

       … while evaluating the option `warnings':

       … while evaluating definitions from `/nix/store/anvdcc2arw7kqrvwnidvhw6ypkkvws68-source/nixos/modules/system/boot/systemd.nix':

       … while evaluating the option `systemd.services.samba-nmbd.serviceConfig':

       … while evaluating definitions from `/nix/store/anvdcc2arw7kqrvwnidvhw6ypkkvws68-source/nixos/modules/services/network-filesystems/samba.nix':

       … while calculating requiredPythonModules for python3.11-cherrypy-18.10.0:

       … while calculating requiredPythonModules for python3.11-jaraco-collections-5.2.1:

       … while calculating requiredPythonModules for python3.11-jaraco-text-4.0.0:

       … while calculating requiredPythonModules for python3.11-inflect-7.5.0:

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: sphinx-9.1.0 not supported for interpreter python3.11
Command 'nix --extra-experimental-features 'nix-command flakes' build --print-out-paths '.#nixosConfigurations."tank".config.system.build.toplevel' --no-link' returned non-zero exit status 1.